TLDR: see the [[https://vindarel.github.io/cl-torrents/tutorial.html][tutorial]] !

* cl-torrents

  This is a  little tool for the  lisp REPL to search  for torrents on
  the Pirate Bay (piratebay.to):

** Installation

   This  is not  distributed with  Quicklisp (yet?).  Clone this  repo
   where Quicklisp can find it:

: git clone git@github.com:vindarel/cl-torrents.git ~/quicklisp/local-projects/

and load it:

: (ql:quickload "cl-torrents")

** Usage

   Search for torrents:

#+BEGIN_SRC text
(torrents "matrix")
  [...]
  6: The Matrix Revolutions (2003) BRRip [Dual Audio] [Hindi+Eng]
  5: Matrix (1999)Blu-Ray 720p Dublado PT-BR - mo93438
  4: The Matrix Trilogy (1999-2003) BDRip 1080p Dual Audio [ Hind
  3: The Matrix Trilogy (1999-2003) BluRay BDRip 1080p AC3
  2: The Matrix Trilogy (1999-2003) + Extras 1080p BluRay x264 Du
  1: The Matrix Reloaded (2003) FullHD, Dual Audio: English + Spa
  0: Matrix FRENCH DVDRIP 1999 COOL
#+END_SRC

  For each result title, your keywords are colored in blue.

  Get a magnet link with:

#+BEGIN_SRC lisp
(magnet 0)
;; "magnet:?xt=urn:btih:40eca43690cf1b99b0a4d485ebf4855d20b0bac5"
#+END_SRC

  It could be more featureful. But our goal was to write a tutorial to
  show you diverse Common Lisp topics.

** Settings

Maximum number  of results  to print (50  by default  for convenience,
when there can be more than a hundred results).

: (setf *nb-results* 50)

** Tutorial

   Writing   a   little   web   scraper   like   this   one   is   not
   difficult. However, I had to spend  some time to find out the right
   libraries and resources.  It is also  not trivial at first to start
   a  Lisp project.  So this  tutorial is  a mix  of hopefully  useful
   stuff:

- web scraping,
- trying out things at the REPL,
- creating and loading a project,
- basic data structures and gotchas,
- some useful libraries,
- unit tests, with mocks,
- where to find documentation,
- ...

  It  will  eventually  tackel  more  topics  and  features  (building
  executables,  sharing our  software, more  settings, working  with a
  local copy of TPB…) but in the meanwhile, read

  the [[https://vindarel.github.io/cl-torrents/tutorial.html][tutorial]] !

** Theme

  The tutorial was built with https://github.com/fniessen/org-html-themes.


* Resources

  Don't miss these good resources:

- http://lisp-lang.org/
- [[https://github.com/CodyReichert/awesome-cl][awesome-cl]]
- [[https://lispcookbook.github.io/cl-cookbook/][the Common Lisp Cookbook]]
- http://quickdocs.org/


* Setting up a Common Lisp environment

  The  easiest solution  of all  is to  try [[https://portacle.github.io/][Portacle]],  a portable  and
  multiplatform CL  environment shipping: Emacs25 and  Slime (slightly
  customized), SBCL, Quicklisp and Git.

  Otherwise:

: apt install sbcl rlwrap
: rlwrap sbcl

   and install Quicklisp (two commands) and Slime for Emacs (in MELPA,
   with   package.el)  or   try  Atom-slime   or  Vim   package.   See
   [[http://lisp-lang.org/wiki/article/editors][http://lisp-lang.org/wiki/article/editors]].
